name: Bug report
description: Report a reproducible problem in the app
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue.
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the problem and expected behavior.
      placeholder: Tell us what you see and what you expected.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Configure ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: e.g. 1.0.0+1
  - type: input
    id: flutter_version
    attributes:
      label: Flutter version
      placeholder: e.g. 3.38.9
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell
